# Generated by Django 5.2.14 on 2026-06-03 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('method', models.CharField(default='GET', max_length=16)),
                ('path', models.CharField(max_length=1024)),
                ('curl', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('body_text', models.TextField(blank=True)),
                ('extractors', models.JSONField(blank=True, default=list)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_capabilities', to='projects.environment')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
