# Generated by Django 5.2.14 on 2026-06-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_datafactorycapability_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='pre_request_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='environment',
            name='pre_request_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='environment',
            name='token_session',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
