# Generated by Django 5.2.15 on 2026-06-09 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_pre_request_operations(apps, schema_editor):
    Environment = apps.get_model("projects", "Environment")
    EnvironmentPreRequestOperation = apps.get_model("projects", "EnvironmentPreRequestOperation")
    Platform = apps.get_model("projects", "Platform")
    all_platforms = [str(item).upper() for item in Platform.objects.filter(is_active=True).values_list("code", flat=True)]
    for environment in Environment.objects.filter(pre_request_enabled=True):
        config = environment.pre_request_config or {}
        if not isinstance(config, dict) or not config:
            continue
        platforms = []
        target_platform = config.get("platform")
        if target_platform:
            platforms = [str(target_platform).upper()]
        elif environment.platform_base_urls:
            platforms = [str(item).upper() for item in environment.platform_base_urls.keys()]
        else:
            platforms = [str(item).upper() for item in environment.project.platforms or []] or all_platforms
        EnvironmentPreRequestOperation.objects.create(
            environment=environment,
            name="默认前置操作",
            is_enabled=True,
            platforms=platforms,
            config=config,
            sort_order=0,
            created_by=environment.created_by,
            updated_by=environment.updated_by,
        )
        environment.pre_request_enabled = False
        environment.save(update_fields=["pre_request_enabled"])


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_apicase_created_by_apicase_updated_by_and_more'),
        ('projects', '0005_environment_pre_request_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentPreRequestOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_request_operations', to='projects.environment')),
                ('modules', models.ManyToManyField(blank=True, related_name='pre_request_operations', to='api_testing.apimodule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'ordering': ['environment_id', 'sort_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_legacy_pre_request_operations, migrations.RunPython.noop),
    ]
