# Generated by Django 5.2.14 on 2026-06-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_databaseconnection_testdatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=16),
        ),
    ]
