# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_environmentrequestcontrol'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='project',
            table_comment='项目表：平台内业务项目的基础配置。',
        ),
        migrations.AlterModelTableComment(
            name='platform',
            table_comment='平台表：ERP/WMS/PDA等业务平台字典。',
        ),
        migrations.AlterModelTableComment(
            name='environment',
            table_comment='环境表：维护测试/预发/生产等运行环境和基础变量。',
        ),
        migrations.AlterModelTableComment(
            name='environmentvariable',
            table_comment='环境变量表：按环境和平台维护可引用变量。',
        ),
        migrations.AlterModelTableComment(
            name='environmentprerequestoperation',
            table_comment='环境全局前置操作表：按环境配置登录鉴权等前置请求。',
        ),
        migrations.AlterModelTableComment(
            name='environmentrequestcontrol',
            table_comment='环境请求控件表：限制指定环境允许执行的HTTP请求方式。',
        ),
        migrations.AlterModelTableComment(
            name='databaseconnection',
            table_comment='数据库连接表：测试数据源使用的数据库连接配置。',
        ),
        migrations.AlterModelTableComment(
            name='datafactorycapability',
            table_comment='数据制造能力表：通过接口调用生成测试数据并提取变量。',
        ),
        migrations.AlterModelTableComment(
            name='testdatasource',
            table_comment='测试数据源表：通过SQL等方式准备测试数据并提取变量。',
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], db_comment='数据库类型。', default='mysql', max_length=16),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='description',
            field=models.TextField(blank=True, db_comment='连接说明。'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='env_prefix',
            field=models.SlugField(db_comment='数据库连接环境变量前缀。', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='environment',
            field=models.ForeignKey(db_comment='所属环境ID。', on_delete=django.db.models.deletion.CASCADE, related_name='database_connections', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='last_check_message',
            field=models.CharField(blank=True, db_comment='最近连接检测消息。', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='last_check_status',
            field=models.CharField(choices=[('unchecked', 'Unchecked'), ('success', 'Success'), ('failed', 'Failed')], db_comment='最近连接检测状态。', default='unchecked', max_length=16),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_comment='最近检测时间。', null=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(db_comment='数据库连接名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='body',
            field=models.JSONField(blank=True, db_comment='请求体JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='body_text',
            field=models.TextField(blank=True, db_comment='请求体文本。'),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='curl',
            field=models.TextField(blank=True, db_comment='原始curl文本。'),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='description',
            field=models.TextField(blank=True, db_comment='能力说明。'),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='默认运行环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_capabilities', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='extractors',
            field=models.JSONField(blank=True, db_comment='变量提取规则。', default=list),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='headers',
            field=models.JSONField(blank=True, db_comment='请求头配置。', default=list),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='last_result',
            field=models.JSONField(blank=True, db_comment='最近一次执行结果。', default=dict),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='method',
            field=models.CharField(db_comment='HTTP请求方式。', default='GET', max_length=16),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='name',
            field=models.CharField(db_comment='能力名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='path',
            field=models.CharField(db_comment='请求路径或完整URL。', max_length=1024),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='platform',
            field=models.CharField(blank=True, db_comment='所属平台编码。', max_length=32),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='query_params',
            field=models.JSONField(blank=True, db_comment='查询参数配置。', default=list),
        ),
        migrations.AlterField(
            model_name='datafactorycapability',
            name='run_count',
            field=models.PositiveIntegerField(db_comment='执行次数。', default=0),
        ),
        migrations.AlterField(
            model_name='environment',
            name='base_url',
            field=models.URLField(blank=True, db_comment='环境默认Base URL。'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='env_type',
            field=models.CharField(choices=[('dev', 'Dev'), ('test', 'Test'), ('staging', 'Staging'), ('prod', 'Prod')], db_comment='环境类型：dev/test/staging/prod。', default='test', max_length=16),
        ),
        migrations.AlterField(
            model_name='environment',
            name='headers',
            field=models.JSONField(blank=True, db_comment='环境级默认请求头。', default=dict),
        ),
        migrations.AlterField(
            model_name='environment',
            name='is_default',
            field=models.BooleanField(db_comment='是否默认环境。', default=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='is_readonly',
            field=models.BooleanField(db_comment='是否只读环境。', default=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(db_comment='环境名称。', max_length=64),
        ),
        migrations.AlterField(
            model_name='environment',
            name='platform_base_urls',
            field=models.JSONField(blank=True, db_comment='不同平台的Base URL映射。', default=dict),
        ),
        migrations.AlterField(
            model_name='environment',
            name='pre_request_config',
            field=models.JSONField(blank=True, db_comment='旧版全局前置操作配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='environment',
            name='pre_request_enabled',
            field=models.BooleanField(db_comment='是否启用旧版全局前置操作。', default=False),
        ),
        migrations.AlterField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='secret_variables',
            field=models.JSONField(blank=True, db_comment='环境敏感变量JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='environment',
            name='token_session',
            field=models.JSONField(blank=True, db_comment='前置登录缓存的Token会话信息。', default=dict),
        ),
        migrations.AlterField(
            model_name='environment',
            name='variables',
            field=models.JSONField(blank=True, db_comment='环境基础变量JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='config',
            field=models.JSONField(blank=True, db_comment='前置操作配置JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='environment',
            field=models.ForeignKey(db_comment='所属环境ID。', on_delete=django.db.models.deletion.CASCADE, related_name='pre_request_operations', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='is_enabled',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='name',
            field=models.CharField(db_comment='前置操作名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='platforms',
            field=models.JSONField(blank=True, db_comment='生效平台编码列表。', default=list),
        ),
        migrations.AlterField(
            model_name='environmentprerequestoperation',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='执行排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='environmentrequestcontrol',
            name='description',
            field=models.CharField(blank=True, db_comment='控件说明。', max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentrequestcontrol',
            name='environment',
            field=models.ForeignKey(db_comment='所属环境ID。', on_delete=django.db.models.deletion.CASCADE, related_name='request_controls', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='environmentrequestcontrol',
            name='is_enabled',
            field=models.BooleanField(db_comment='是否启用请求控件。', default=True),
        ),
        migrations.AlterField(
            model_name='environmentrequestcontrol',
            name='methods',
            field=models.JSONField(blank=True, db_comment='允许执行的HTTP方法列表。', default=list),
        ),
        migrations.AlterField(
            model_name='environmentrequestcontrol',
            name='name',
            field=models.CharField(db_comment='控件名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='description',
            field=models.CharField(blank=True, db_comment='变量说明。', max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='environment',
            field=models.ForeignKey(db_comment='所属环境ID。', on_delete=django.db.models.deletion.CASCADE, related_name='variable_items', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='is_enabled',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='is_secret',
            field=models.BooleanField(db_comment='是否敏感变量。', default=False),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='key',
            field=models.CharField(db_comment='变量Key，用于{{变量名}}引用。', max_length=128),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='platform',
            field=models.CharField(blank=True, db_comment='平台编码，空表示环境通用变量。', max_length=16),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='scope',
            field=models.CharField(db_comment='变量作用域。', default='environment', max_length=32),
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='value',
            field=models.TextField(blank=True, db_comment='变量值。'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='code',
            field=models.SlugField(db_comment='平台编码。', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, db_comment='平台说明。'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(db_comment='平台名称。', max_length=64),
        ),
        migrations.AlterField(
            model_name='platform',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(db_comment='项目编码。', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, db_comment='项目说明。'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_comment='项目名称。', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='platforms',
            field=models.JSONField(blank=True, db_comment='项目启用的平台编码列表。', default=list),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='database_connection',
            field=models.ForeignKey(blank=True, db_comment='使用的数据库连接ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_sources', to='projects.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='description',
            field=models.TextField(blank=True, db_comment='数据源说明。'),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='所属环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_data_sources', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='extractors',
            field=models.JSONField(blank=True, db_comment='从结果集中提取变量的规则。', default=list),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='last_result',
            field=models.JSONField(blank=True, db_comment='最近一次试运行结果。', default=dict),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='name',
            field=models.CharField(db_comment='数据源名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='test_data_sources', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='run_count',
            field=models.PositiveIntegerField(db_comment='试运行次数。', default=0),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='source_type',
            field=models.CharField(choices=[('database_query', 'Database query')], db_comment='数据源类型。', default='database_query', max_length=32),
        ),
        migrations.AlterField(
            model_name='testdatasource',
            name='sql',
            field=models.TextField(blank=True, db_comment='数据源SQL。'),
        ),
    ]
