# Generated by Django 5.2.15 on 2026-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_databaseconnection_inline_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='database_name',
            field=models.CharField(blank=True, db_comment='数据库名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='env_prefix',
            field=models.SlugField(blank=True, db_comment='历史兼容字段，不再作为运行期配置来源。', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(blank=True, db_comment='数据库主机地址。', max_length=255),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password_ciphertext',
            field=models.TextField(blank=True, db_comment='数据库密码密文。'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.PositiveIntegerField(db_comment='数据库端口。', default=3306),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='username',
            field=models.CharField(blank=True, db_comment='数据库账号。', max_length=128),
        ),
    ]
