# Generated by Django 5.2.14 on 2026-05-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(default='P1', max_length=8)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['suite_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('ERP', 'ERP'), ('WMS', 'WMS'), ('PDA', 'PDA'), ('CLIENT', 'Client')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_testing.apimodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_modules', to='projects.project')),
            ],
            options={
                'ordering': ['platform', 'sort_order', 'id'],
                'unique_together': {('project', 'platform', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('ERP', 'ERP'), ('WMS', 'WMS'), ('PDA', 'PDA'), ('CLIENT', 'Client')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('developing', 'Developing'), ('released', 'Released'), ('deprecated', 'Deprecated')], default='developing', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('body_type', models.CharField(default='none', max_length=32)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('body_schema', models.JSONField(blank=True, default=dict)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('response_example', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_definitions', to='projects.project')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='api_testing.apimodule')),
            ],
            options={
                'ordering': ['platform', 'module_id', 'sort_order', 'id'],
                'unique_together': {('project', 'platform', 'method', 'path')},
            },
        ),
        migrations.CreateModel(
            name='ApiStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('platform', models.CharField(choices=[('ERP', 'ERP'), ('WMS', 'WMS'), ('PDA', 'PDA'), ('CLIENT', 'Client')], default='ERP', max_length=16)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('query_params', models.JSONField(blank=True, default=list)),
                ('body_type', models.CharField(default='none', max_length=32)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('pre_script', models.TextField(blank=True)),
                ('post_script', models.TextField(blank=True)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('extractors', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api_testing.apidefinition')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_testing.apiscenario')),
            ],
            options={
                'ordering': ['scenario_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_suites', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='apiscenario',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api_testing.apisuite'),
        ),
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('extractors', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api_testing.apisuite')),
            ],
            options={
                'ordering': ['suite_id', 'sort_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='apiscenario',
            unique_together={('suite', 'name')},
        ),
    ]
