# Generated by Django 5.2.14 on 2026-06-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0001_initial'),
        ('projects', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodule',
            name='code',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='managed_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_modules', to='projects.platform'),
        ),
    ]
