# Generated by Django 5.2.14 on 2026-06-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0002_apimodule_code_apimodule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidefinition',
            name='platform',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='platform',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='platform',
            field=models.CharField(default='ERP', max_length=32),
        ),
    ]
