# Generated by Django 5.2.14 on 2026-06-02 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0003_alter_apidefinition_platform_and_more'),
        ('projects', '0002_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMockRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='默认 Mock', max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('delay_ms', models.PositiveIntegerField(default=0)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('match_rules', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_rules', to='api_testing.apidefinition')),
            ],
            options={
                'ordering': ['api_id', '-enabled', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=16)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=8)),
                ('request_override', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_testing.apidefinition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project')),
            ],
            options={
                'ordering': ['api_id', 'priority', 'id'],
                'unique_together': {('project', 'api', 'name')},
            },
        ),
    ]
