# Generated by Django 5.2.14 on 2026-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_apicase_created_by_apicase_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='post_data_source_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apistep',
            name='pre_data_source_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='post_data_source_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='pre_data_source_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
