# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_testing", "0006_apistep_post_data_source_ids_and_more"),
        ("projects", "0009_environmentrequestcontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiscenario",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_scenarios",
                to="projects.environment",
            ),
        ),
    ]
