# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0007_apiscenario_environment'),
        ('projects', '0010_alter_databaseconnection_db_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='apimodule',
            table_comment='接口目录表：按平台维护接口的多级模块/目录结构。',
        ),
        migrations.AlterModelTableComment(
            name='apidefinition',
            table_comment='接口定义表：维护平台接口的请求方式、路径、请求结构和示例。',
        ),
        migrations.AlterModelTableComment(
            name='apitestcase',
            table_comment='单接口测试用例表：绑定某个接口的功能用例和请求覆盖配置。',
        ),
        migrations.AlterModelTableComment(
            name='apimockrule',
            table_comment='接口Mock规则表：维护接口模拟响应和匹配规则。',
        ),
        migrations.AlterModelTableComment(
            name='apisuite',
            table_comment='接口测试套件表：组织接口用例和场景的集合。',
        ),
        migrations.AlterModelTableComment(
            name='apiscenario',
            table_comment='接口场景用例表：按业务流程编排多个接口步骤。',
        ),
        migrations.AlterModelTableComment(
            name='apistep',
            table_comment='场景接口步骤表：场景内单个接口步骤的请求、断言和变量提取配置。',
        ),
        migrations.AlterModelTableComment(
            name='apicase',
            table_comment='旧版接口用例表：按套件保存的接口请求步骤，保留兼容历史功能。',
        ),
        migrations.AlterField(
            model_name='apicase',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='断言配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='body',
            field=models.JSONField(blank=True, db_comment='请求体。', default=dict),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='extractors',
            field=models.JSONField(blank=True, db_comment='变量提取规则。', default=list),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='headers',
            field=models.JSONField(blank=True, db_comment='请求头配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_comment='HTTP请求方式。', default='GET', max_length=16),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='name',
            field=models.CharField(db_comment='用例名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='path',
            field=models.CharField(db_comment='请求路径或完整URL。', max_length=512),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='query_params',
            field=models.JSONField(blank=True, db_comment='查询参数配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='suite',
            field=models.ForeignKey(db_comment='所属接口测试套件ID。', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api_testing.apisuite'),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='接口默认断言配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='auth_config',
            field=models.JSONField(blank=True, db_comment='接口鉴权配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='body',
            field=models.JSONField(blank=True, db_comment='默认请求体。', default=dict),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='body_schema',
            field=models.JSONField(blank=True, db_comment='请求体结构描述。', default=dict),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='body_type',
            field=models.CharField(db_comment='请求体类型。', default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='description',
            field=models.TextField(blank=True, db_comment='接口说明。'),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='headers',
            field=models.JSONField(blank=True, db_comment='默认请求头配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_comment='HTTP请求方式。', default='GET', max_length=16),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='module',
            field=models.ForeignKey(blank=True, db_comment='所属接口目录ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='api_testing.apimodule'),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='name',
            field=models.CharField(db_comment='接口名称。', max_length=100),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='path',
            field=models.CharField(db_comment='接口路径或完整URL。', max_length=512),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='platform',
            field=models.CharField(db_comment='平台编码，如 ERP/WMS/PDA。', max_length=32),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='api_definitions', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='query_params',
            field=models.JSONField(blank=True, db_comment='默认查询参数配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='response_example',
            field=models.JSONField(blank=True, db_comment='响应示例。', default=dict),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='status',
            field=models.CharField(choices=[('developing', 'Developing'), ('released', 'Released'), ('deprecated', 'Deprecated')], db_comment='接口状态：开发中/已发布/已废弃。', default='developing', max_length=16),
        ),
        migrations.AlterField(
            model_name='apidefinition',
            name='tags',
            field=models.JSONField(blank=True, db_comment='接口标签列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='api',
            field=models.ForeignKey(db_comment='关联接口定义ID。', on_delete=django.db.models.deletion.CASCADE, related_name='mock_rules', to='api_testing.apidefinition'),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='delay_ms',
            field=models.PositiveIntegerField(db_comment='Mock响应延迟毫秒数。', default=0),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='description',
            field=models.TextField(blank=True, db_comment='规则说明。'),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='enabled',
            field=models.BooleanField(db_comment='是否启用该Mock规则。', default=False),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='headers',
            field=models.JSONField(blank=True, db_comment='Mock响应头。', default=list),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='match_rules',
            field=models.JSONField(blank=True, db_comment='Mock匹配规则。', default=list),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='name',
            field=models.CharField(db_comment='Mock规则名称。', default='默认 Mock', max_length=128),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='response_body',
            field=models.JSONField(blank=True, db_comment='Mock响应体。', default=dict),
        ),
        migrations.AlterField(
            model_name='apimockrule',
            name='status_code',
            field=models.PositiveSmallIntegerField(db_comment='Mock响应状态码。', default=200),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='code',
            field=models.SlugField(blank=True, db_comment='目录编码。', max_length=32),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='description',
            field=models.TextField(blank=True, db_comment='目录说明。'),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='managed_platform',
            field=models.ForeignKey(blank=True, db_comment='关联的平台管理记录。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_modules', to='projects.platform'),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='name',
            field=models.CharField(db_comment='目录名称。', max_length=100),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='父级接口目录ID，空表示顶级目录。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_testing.apimodule'),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='platform',
            field=models.CharField(db_comment='平台编码，如 ERP/WMS/PDA。', max_length=32),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='api_modules', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='apimodule',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='目录排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='description',
            field=models.TextField(blank=True, db_comment='场景说明。'),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='场景默认运行环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_scenarios', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='name',
            field=models.CharField(db_comment='场景名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='priority',
            field=models.CharField(db_comment='优先级。', default='P1', max_length=8),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='suite',
            field=models.ForeignKey(db_comment='所属接口测试套件ID。', on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api_testing.apisuite'),
        ),
        migrations.AlterField(
            model_name='apiscenario',
            name='tags',
            field=models.JSONField(blank=True, db_comment='场景标签列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='api',
            field=models.ForeignKey(blank=True, db_comment='继承来源接口定义ID，可为空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api_testing.apidefinition'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='步骤断言配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='auth_config',
            field=models.JSONField(blank=True, db_comment='步骤鉴权配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='body',
            field=models.JSONField(blank=True, db_comment='步骤请求体。', default=dict),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='body_type',
            field=models.CharField(db_comment='请求体类型。', default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='extractors',
            field=models.JSONField(blank=True, db_comment='响应变量提取规则。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='headers',
            field=models.JSONField(blank=True, db_comment='步骤请求头配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_comment='HTTP请求方式。', default='GET', max_length=16),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='name',
            field=models.CharField(db_comment='步骤名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='path',
            field=models.CharField(db_comment='请求路径或完整URL。', max_length=512),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='platform',
            field=models.CharField(db_comment='步骤所属平台编码。', default='ERP', max_length=32),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='post_data_source_ids',
            field=models.JSONField(blank=True, db_comment='步骤执行后运行的数据源ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='post_script',
            field=models.TextField(blank=True, db_comment='步骤后置脚本。'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='pre_data_source_ids',
            field=models.JSONField(blank=True, db_comment='步骤执行前运行的数据源ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='pre_script',
            field=models.TextField(blank=True, db_comment='步骤前置脚本。'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='query_params',
            field=models.JSONField(blank=True, db_comment='步骤查询参数配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='scenario',
            field=models.ForeignKey(db_comment='所属场景ID。', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api_testing.apiscenario'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='步骤排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='description',
            field=models.TextField(blank=True, db_comment='套件说明。'),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='name',
            field=models.CharField(db_comment='套件名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='platforms',
            field=models.JSONField(blank=True, db_comment='套件覆盖的平台编码列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='api_suites', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='apisuite',
            name='tags',
            field=models.JSONField(blank=True, db_comment='套件标签列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='api',
            field=models.ForeignKey(db_comment='关联接口定义ID。', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_testing.apidefinition'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='用例断言配置。', default=list),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='description',
            field=models.TextField(blank=True, db_comment='用例说明。'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='name',
            field=models.CharField(db_comment='用例名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='post_data_source_ids',
            field=models.JSONField(blank=True, db_comment='后置测试数据源ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='pre_data_source_ids',
            field=models.JSONField(blank=True, db_comment='前置测试数据源ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], db_comment='优先级。', default='P1', max_length=8),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='request_override',
            field=models.JSONField(blank=True, db_comment='覆盖接口默认请求的配置。', default=dict),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], db_comment='用例状态：草稿/启用/停用。', default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='apitestcase',
            name='variables',
            field=models.JSONField(blank=True, db_comment='用例变量配置。', default=list),
        ),
    ]
