# Generated by Django 5.2.15 on 2026-07-21 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_batch_import_capability(apps, schema_editor):
    Capability = apps.get_model("api_testing", "OpenApiCapability")
    Capability.objects.get_or_create(
        code="api_definition.batch_import",
        defaults={
            "name": "批量导入接口资产",
            "version": "v1",
            "method": "POST",
            "path": "/api/v1/api-definitions/batch-import/",
            "required_permission": "api.import",
            "documentation": {
                "overview": "用于将历史接口资产批量导入平台。",
                "headers": [
                    {"name": "Authorization", "required": True, "description": "Token <access_token>"},
                    {"name": "Content-Type", "required": True, "description": "application/json"},
                ],
                "request_fields": [
                    {"name": "module_code", "type": "string", "required": True, "description": "模块管理中的唯一模块编码"},
                    {"name": "items", "type": "array", "required": True, "description": "待导入接口列表"},
                    {"name": "items[].name", "type": "string", "required": True, "description": "接口名称，最大 100 字符"},
                    {"name": "items[].path", "type": "string", "required": True, "description": "接口路径，最大 512 字符"},
                    {"name": "items[].method", "type": "string", "required": True, "description": "GET、POST、PUT、PATCH、DELETE"},
                    {"name": "items[].params", "type": "object", "required": True, "description": "GET/DELETE 写入查询参数；POST/PUT/PATCH 写入 JSON 请求体"},
                ],
                "request_example": {
                    "module_code": "order-management",
                    "items": [{
                        "name": "创建订单",
                        "path": "/api/orders",
                        "method": "POST",
                        "params": {"customer_id": "${customer_id}", "items": []},
                    }],
                },
                "error_cases": [{"code": "MODULE_NOT_FOUND", "message": "模块编码不存在或已停用"}],
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0012_apisuite_member_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodule',
            name='code',
            field=models.SlugField(db_comment='目录编码。', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='ApiImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_no', models.CharField(max_length=40, unique=True)),
                ('module_code', models.CharField(max_length=32)),
                ('module_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '处理中'), ('completed', '已完成'), ('completed_with_errors', '部分完成'), ('failed', '处理失败')], default='queued', max_length=32)),
                ('total', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('limit_snapshot', models.PositiveIntegerField(default=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='api_testing.apimodule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table_comment': '接口资产导入批次表。',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sequence_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('normalized_path', models.CharField(max_length=512)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '已导入'), ('skipped', '已跳过'), ('failed', '处理失败')], default='pending', max_length=16)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='api_testing.apidefinition')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_testing.apiimportbatch')),
            ],
            options={
                'db_table_comment': '接口资产导入明细表。',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='OpenApiCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='v1', max_length=16)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('documentation', models.JSONField(default=dict)),
                ('required_permission', models.CharField(max_length=96)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'db_table_comment': '开放接口能力表：维护对外接口说明书与启停状态。',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpenApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('request_id', models.CharField(max_length=40, unique=True)),
                ('capability_code', models.CharField(max_length=96)),
                ('capability_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', '调用成功'), ('business_failed', '业务失败'), ('auth_failed', '鉴权失败'), ('system_failed', '系统异常')], max_length=24)),
                ('result_summary', models.JSONField(default=dict)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_api_call_logs', to=settings.AUTH_USER_MODEL)),
                ('related_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='api_testing.apiimportbatch')),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='api_testing.openapicapability')),
            ],
            options={
                'db_table_comment': '开放接口调用日志表。',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apiimportbatch',
            index=models.Index(fields=['status', 'created_at'], name='api_testing_status_17834d_idx'),
        ),
        migrations.AddIndex(
            model_name='apiimportbatch',
            index=models.Index(fields=['module_code', 'created_at'], name='api_testing_module__934f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='apiimportbatch',
            index=models.Index(fields=['created_by', 'created_at'], name='api_testing_created_719de6_idx'),
        ),
        migrations.AddIndex(
            model_name='apiimportitem',
            index=models.Index(fields=['batch', 'status'], name='api_testing_batch_i_05c90a_idx'),
        ),
        migrations.AddConstraint(
            model_name='apiimportitem',
            constraint=models.UniqueConstraint(fields=('batch', 'sequence_no'), name='uniq_api_import_item_sequence'),
        ),
        migrations.AddIndex(
            model_name='openapicalllog',
            index=models.Index(fields=['capability_code', 'created_at'], name='api_testing_capabil_cab55c_idx'),
        ),
        migrations.AddIndex(
            model_name='openapicalllog',
            index=models.Index(fields=['status', 'created_at'], name='api_testing_status_c3c66a_idx'),
        ),
        migrations.AddIndex(
            model_name='openapicalllog',
            index=models.Index(fields=['caller', 'created_at'], name='api_testing_caller__8684e9_idx'),
        ),
        migrations.RunPython(seed_batch_import_capability, migrations.RunPython.noop),
    ]
