# Generated by Django 5.2.15 on 2026-07-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0016_update_internal_api_documentation'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='openapicalllog',
            table_comment='内部接口调用日志表。',
        ),
        migrations.AlterModelTableComment(
            name='openapicapability',
            table_comment='内部接口说明表：维护平台内部接口的使用说明。',
        ),
    ]
