import { http } from "@/api/http";
import { getOrLoadResource, invalidateResource } from "@/api/resourceCache";

export interface ListResponse<T> {
  count: number;
  results: T[];
}

export const unwrapList = <T>(data: ListResponse<T> | T[]): T[] => {
  return Array.isArray(data) ? data : data.results;
};

export const platformApi = {
  platforms: () => http.get("/platforms/"),
  cachedPlatforms: () => getOrLoadResource("platform:platforms", async () => (await http.get("/platforms/", { cache: false })).data),
  createPlatform: (payload: Record<string, unknown>) => http.post("/platforms/", payload),
  updatePlatform: (id: number, payload: Record<string, unknown>) => http.patch(`/platforms/${id}/`, payload),
  deletePlatform: (id: number) => http.delete(`/platforms/${id}/`),
  projects: () => http.get("/projects/"),
  cachedProjects: () => getOrLoadResource("platform:projects", async () => (await http.get("/projects/", { cache: false })).data),
  createProject: (payload: Record<string, unknown>) => http.post("/projects/", payload),
  updateProject: (id: number, payload: Record<string, unknown>) => http.patch(`/projects/${id}/`, payload),
  deleteProject: (id: number) => http.delete(`/projects/${id}/`),
  environments: () => http.get("/environments/"),
  cachedEnvironments: () => getOrLoadResource("platform:environments", async () => (await http.get("/environments/", { cache: false })).data),
  createEnvironment: (payload: Record<string, unknown>) => http.post("/environments/", payload),
  updateEnvironment: (id: number, payload: Record<string, unknown>) => http.patch(`/environments/${id}/`, payload),
  deleteEnvironment: (id: number) => http.delete(`/environments/${id}/`),
  environmentVariables: (params?: Record<string, unknown>) => http.get("/environment-variables/", { params }),
  createEnvironmentVariable: (payload: Record<string, unknown>) => http.post("/environment-variables/", payload),
  updateEnvironmentVariable: (id: number, payload: Record<string, unknown>) => http.patch(`/environment-variables/${id}/`, payload),
  deleteEnvironmentVariable: (id: number) => http.delete(`/environment-variables/${id}/`),
  environmentPreRequestOperations: (params?: Record<string, unknown>) => http.get("/environment-pre-request-operations/", { params }),
  createEnvironmentPreRequestOperation: (payload: Record<string, unknown>) => http.post("/environment-pre-request-operations/", payload),
  updateEnvironmentPreRequestOperation: (id: number, payload: Record<string, unknown>) => http.patch(`/environment-pre-request-operations/${id}/`, payload),
  deleteEnvironmentPreRequestOperation: (id: number) => http.delete(`/environment-pre-request-operations/${id}/`),
  environmentRequestControls: (params?: Record<string, unknown>) => http.get("/environment-request-controls/", { params }),
  createEnvironmentRequestControl: (payload: Record<string, unknown>) => http.post("/environment-request-controls/", payload),
  updateEnvironmentRequestControl: (id: number, payload: Record<string, unknown>) => http.patch(`/environment-request-controls/${id}/`, payload),
  deleteEnvironmentRequestControl: (id: number) => http.delete(`/environment-request-controls/${id}/`),
  databaseConnections: (params?: Record<string, unknown>) => http.get("/database-connections/", { params }),
  createDatabaseConnection: (payload: Record<string, unknown>) => http.post("/database-connections/", payload),
  updateDatabaseConnection: (id: number, payload: Record<string, unknown>) => http.patch(`/database-connections/${id}/`, payload),
  deleteDatabaseConnection: (id: number) => http.delete(`/database-connections/${id}/`),
  checkDatabaseConnection: (id: number) => http.post(`/database-connections/${id}/check/`),
  testDataSources: (params?: Record<string, unknown>) => http.get("/test-data-sources/", { params }),
  createTestDataSource: (payload: Record<string, unknown>) => http.post("/test-data-sources/", payload),
  updateTestDataSource: (id: number, payload: Record<string, unknown>) => http.patch(`/test-data-sources/${id}/`, payload),
  deleteTestDataSource: (id: number) => http.delete(`/test-data-sources/${id}/`),
  runTestDataSource: (id: number, payload?: Record<string, unknown>) => http.post(`/test-data-sources/${id}/run/`, payload || {}, { timeout: 120000 }),
  dataFactoryCapabilities: (params?: Record<string, unknown>) => http.get("/data-factory-capabilities/", { params }),
  createDataFactoryCapability: (payload: Record<string, unknown>) => http.post("/data-factory-capabilities/", payload),
  updateDataFactoryCapability: (id: number, payload: Record<string, unknown>) => http.patch(`/data-factory-capabilities/${id}/`, payload),
  deleteDataFactoryCapability: (id: number) => http.delete(`/data-factory-capabilities/${id}/`),
  apiDefinitions: (params?: Record<string, unknown>) => http.get("/api-definitions/", { params }),
  createApiDefinition: (payload: Record<string, unknown>) => http.post("/api-definitions/", payload),
  updateApiDefinition: (id: number, payload: Record<string, unknown>) => http.patch(`/api-definitions/${id}/`, payload),
  deleteApiDefinition: (id: number) => http.delete(`/api-definitions/${id}/`),
  apiTestCases: (params?: Record<string, unknown>) => http.get("/api-test-cases/", { params }),
  createApiTestCase: (payload: Record<string, unknown>) => http.post("/api-test-cases/", payload),
  updateApiTestCase: (id: number, payload: Record<string, unknown>) => http.patch(`/api-test-cases/${id}/`, payload),
  deleteApiTestCase: (id: number) => http.delete(`/api-test-cases/${id}/`),
  apiMockRules: (params?: Record<string, unknown>) => http.get("/api-mock-rules/", { params }),
  createApiMockRule: (payload: Record<string, unknown>) => http.post("/api-mock-rules/", payload),
  updateApiMockRule: (id: number, payload: Record<string, unknown>) => http.patch(`/api-mock-rules/${id}/`, payload),
  deleteApiMockRule: (id: number) => http.delete(`/api-mock-rules/${id}/`),
  apiModules: () => http.get("/api-modules/"),
  cachedApiModules: () => getOrLoadResource("platform:api-modules", async () => (await http.get("/api-modules/", { cache: false })).data),
  createApiModule: (payload: Record<string, unknown>) => withResourceInvalidation("platform:api-modules", http.post("/api-modules/", payload)),
  updateApiModule: (id: number, payload: Record<string, unknown>) => withResourceInvalidation("platform:api-modules", http.patch(`/api-modules/${id}/`, payload)),
  deleteApiModule: (id: number) => withResourceInvalidation("platform:api-modules", http.delete(`/api-modules/${id}/`)),
  apiSuites: (params?: Record<string, unknown>) => http.get("/api-suites/", { params }),
  cachedApiSuites: (params?: Record<string, unknown>) => getOrLoadResource(`platform:api-suites:${JSON.stringify(params || {})}`, async () => (await http.get("/api-suites/", { params, cache: false })).data),
  createApiSuite: (payload: Record<string, unknown>) => http.post("/api-suites/", payload),
  updateApiSuite: (id: number, payload: Record<string, unknown>) => http.patch(`/api-suites/${id}/`, payload),
  deleteApiSuite: (id: number) => http.delete(`/api-suites/${id}/`),
  apiScenarios: (params?: Record<string, unknown>) => http.get("/api-scenarios/", { params }),
  createApiScenario: (payload: Record<string, unknown>) => http.post("/api-scenarios/", payload),
  updateApiScenario: (id: number, payload: Record<string, unknown>) => http.patch(`/api-scenarios/${id}/`, payload),
  deleteApiScenario: (id: number) => http.delete(`/api-scenarios/${id}/`),
  apiSteps: (params?: Record<string, unknown>) => http.get("/api-steps/", { params }),
  createApiStep: (payload: Record<string, unknown>) => http.post("/api-steps/", payload),
  updateApiStep: (id: number, payload: Record<string, unknown>) => http.patch(`/api-steps/${id}/`, payload),
  deleteApiStep: (id: number) => http.delete(`/api-steps/${id}/`),
  testRuns: () => http.get("/test-runs/", { cache: false }),
  testRun: (id: number) => http.get(`/test-runs/${id}/`, { cache: false }),
  scheduledPlans: (params?: Record<string, unknown>) => http.get("/scheduled-plans/", { params, cache: false }),
  createScheduledPlan: (payload: Record<string, unknown>) => http.post("/scheduled-plans/", payload),
  updateScheduledPlan: (id: number, payload: Record<string, unknown>) => http.patch(`/scheduled-plans/${id}/`, payload),
  deleteScheduledPlan: (id: number) => http.delete(`/scheduled-plans/${id}/`),
  toggleScheduledPlan: (id: number) => http.post(`/scheduled-plans/${id}/toggle/`),
  runScheduledPlanNow: (id: number) => http.post(`/scheduled-plans/${id}/run-now/`, {}, { timeout: 120000 }),
  notificationChannels: (params?: Record<string, unknown>) => http.get("/notification-channels/", { params, cache: false }),
  createNotificationChannel: (payload: Record<string, unknown>) => http.post("/notification-channels/", payload),
  updateNotificationChannel: (id: number, payload: Record<string, unknown>) => http.patch(`/notification-channels/${id}/`, payload),
  deleteNotificationChannel: (id: number) => http.delete(`/notification-channels/${id}/`),
  notificationTemplates: (params?: Record<string, unknown>) => http.get("/notification-templates/", { params, cache: false }),
  createNotificationTemplate: (payload: Record<string, unknown>) => http.post("/notification-templates/", payload),
  updateNotificationTemplate: (id: number, payload: Record<string, unknown>) => http.patch(`/notification-templates/${id}/`, payload),
  deleteNotificationTemplate: (id: number) => http.delete(`/notification-templates/${id}/`),
  notificationTemplateVariables: () => http.get("/notification-templates/variables/", { cache: false }),
  notificationSendLogs: (params?: Record<string, unknown>) => http.get("/notification-send-logs/", { params, cache: false }),
  performanceExecutor: () => http.get("/performance/executor/", { cache: false }),
  performanceScripts: (params?: Record<string, unknown>) => http.get("/performance/scripts/", { params }),
  createPerformanceScript: (payload: FormData) => http.post("/performance/scripts/", payload),
  updatePerformanceScript: (id: number, payload: Record<string, unknown>) => http.patch(`/performance/scripts/${id}/`, payload),
  deletePerformanceScript: (id: number) => http.delete(`/performance/scripts/${id}/`),
  togglePerformanceScript: (id: number) => http.post(`/performance/scripts/${id}/toggle-active/`),
  performanceTasks: (params?: Record<string, unknown>) => http.get("/performance/tasks/", { params }),
  createPerformanceTask: (payload: Record<string, unknown>) => http.post("/performance/tasks/", payload),
  updatePerformanceTask: (id: number, payload: Record<string, unknown>) => http.patch(`/performance/tasks/${id}/`, payload),
  deletePerformanceTask: (id: number) => http.delete(`/performance/tasks/${id}/`),
  runPerformanceTask: (id: number) => http.post(`/performance/tasks/${id}/run/`, {}, { timeout: 120000 }),
  togglePerformanceTask: (id: number) => http.post(`/performance/tasks/${id}/toggle-active/`),
  performanceRuns: (params?: Record<string, unknown>) => http.get("/performance/runs/", { params, cache: false }),
  markPerformanceRunFailed: (id: number) => http.post(`/performance/runs/${id}/mark-failed/`),
  executePerformanceRun: (id: number) => http.post(`/performance/runs/${id}/execute/`, {}, { timeout: 120000 }),
  uiSuites: (params?: Record<string, unknown>) => http.get("/ui-suites/", { params }),
  createUiSuite: (payload: Record<string, unknown>) => http.post("/ui-suites/", payload),
  updateUiSuite: (id: number, payload: Record<string, unknown>) => http.patch(`/ui-suites/${id}/`, payload),
  deleteUiSuite: (id: number) => http.delete(`/ui-suites/${id}/`),
  uiCases: (params?: Record<string, unknown>) => http.get("/ui-cases/", { params }),
  createUiCase: (payload: Record<string, unknown>) => http.post("/ui-cases/", payload),
  updateUiCase: (id: number, payload: Record<string, unknown>) => http.patch(`/ui-cases/${id}/`, payload),
  deleteUiCase: (id: number) => http.delete(`/ui-cases/${id}/`),
  uiElements: (params?: Record<string, unknown>) => http.get("/ui-elements/", { params }),
  createUiElement: (payload: Record<string, unknown>) => http.post("/ui-elements/", payload),
  updateUiElement: (id: number, payload: Record<string, unknown>) => http.patch(`/ui-elements/${id}/`, payload),
  deleteUiElement: (id: number) => http.delete(`/ui-elements/${id}/`),
  validateUiElement: (id: number, payload?: Record<string, unknown>) => http.post(`/ui-elements/${id}/validate/`, payload || {}, { timeout: 120000 }),
  uiPages: (params?: Record<string, unknown>) => http.get("/ui-pages/", { params }),
  createUiPage: (payload: Record<string, unknown>) => http.post("/ui-pages/", payload),
  updateUiPage: (id: number, payload: Record<string, unknown>) => http.patch(`/ui-pages/${id}/`, payload),
  deleteUiPage: (id: number) => http.delete(`/ui-pages/${id}/`),
  uiActions: (params?: Record<string, unknown>) => http.get("/ui-actions/", { params }),
  createUiAction: (payload: Record<string, unknown>) => http.post("/ui-actions/", payload),
  updateUiAction: (id: number, payload: Record<string, unknown>) => http.patch(`/ui-actions/${id}/`, payload),
  deleteUiAction: (id: number) => http.delete(`/ui-actions/${id}/`),
  runUiCase: (id: number, payload?: Record<string, unknown>) => http.post(`/ui-cases/${id}/run/`, payload || {}, { timeout: 120000 }),
  debugApi: (payload: Record<string, unknown>) => http.post("/api-definitions/debug/", payload),
};

const withResourceInvalidation = async <T>(key: string, request: Promise<T>) => {
  const response = await request;
  invalidateResource(key);
  return response;
};
