# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='jmeterscript',
            table_comment='性能测试脚本表：保存上传的JMeter JMX脚本文件。',
        ),
        migrations.AlterModelTableComment(
            name='performancetask',
            table_comment='性能测试任务表：基于JMeter脚本配置线程、循环和持续时间。',
        ),
        migrations.AlterModelTableComment(
            name='performancerun',
            table_comment='性能测试执行记录表：一次性能任务运行的状态、报告和日志。',
        ),
        migrations.AlterField(
            model_name='jmeterscript',
            name='description',
            field=models.TextField(blank=True, db_comment='脚本说明。'),
        ),
        migrations.AlterField(
            model_name='jmeterscript',
            name='file',
            field=models.FileField(db_comment='JMX脚本文件路径。', upload_to='performance/jmx/'),
        ),
        migrations.AlterField(
            model_name='jmeterscript',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='jmeterscript',
            name='name',
            field=models.CharField(db_comment='脚本名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_comment='异步任务ID。', max_length=128),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='duration_ms',
            field=models.PositiveIntegerField(db_comment='总耗时毫秒。', default=0),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='error_message',
            field=models.TextField(blank=True, db_comment='失败错误信息。'),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_comment='结束时间。', null=True),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='html_report_dir',
            field=models.CharField(blank=True, db_comment='HTML报告目录。', max_length=512),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='jtl_path',
            field=models.CharField(blank=True, db_comment='JMeter JTL结果文件路径。', max_length=512),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='logs',
            field=models.JSONField(blank=True, db_comment='执行日志列表。', default=list),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='开始时间。', null=True),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_comment='执行状态。', default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='summary',
            field=models.JSONField(blank=True, db_comment='性能摘要数据。', default=dict),
        ),
        migrations.AlterField(
            model_name='performancerun',
            name='task',
            field=models.ForeignKey(db_comment='关联性能任务ID。', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='performance_testing.performancetask'),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='description',
            field=models.TextField(blank=True, db_comment='任务说明。'),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='duration_seconds',
            field=models.PositiveIntegerField(db_comment='持续执行秒数。', default=60),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='loops',
            field=models.PositiveIntegerField(db_comment='循环次数。', default=1),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='name',
            field=models.CharField(db_comment='任务名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='ramp_up_seconds',
            field=models.PositiveIntegerField(db_comment='启动预热秒数。', default=10),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='script',
            field=models.ForeignKey(db_comment='关联JMeter脚本ID。', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='performance_testing.jmeterscript'),
        ),
        migrations.AlterField(
            model_name='performancetask',
            name='threads',
            field=models.PositiveIntegerField(db_comment='线程数。', default=10),
        ),
    ]
