# Generated by Django 5.2.14 on 2026-06-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='操作名称')),
                ('action', models.CharField(choices=[('goto', '打开页面'), ('click', '点击'), ('fill', '输入'), ('press', '按键'), ('select', '下拉选择'), ('check', '勾选'), ('uncheck', '取消勾选'), ('wait', '等待'), ('assert_visible', '断言可见'), ('assert_text', '断言文本'), ('assert_url', '断言 URL'), ('screenshot', '截图')], default='click', max_length=32, verbose_name='动作')),
                ('default_value', models.CharField(blank=True, max_length=512, verbose_name='默认输入/期望')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': 'UI元素操作',
                'verbose_name_plural': 'UI元素操作',
                'ordering': ['action', 'name'],
                'unique_together': {('name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UiElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='元素名称')),
                ('page', models.CharField(blank=True, max_length=128, verbose_name='页面')),
                ('locator_type', models.CharField(choices=[('css', 'CSS'), ('text', 'Text'), ('role', 'Role'), ('xpath', 'XPath'), ('test_id', 'TestId')], default='css', max_length=32, verbose_name='定位方式')),
                ('selector', models.CharField(max_length=512, verbose_name='定位表达式')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ui_testing.uisuite', verbose_name='套件')),
            ],
            options={
                'verbose_name': 'UI定位元素',
                'verbose_name_plural': 'UI定位元素',
                'ordering': ['suite_id', 'page', 'name'],
                'unique_together': {('suite', 'name')},
            },
        ),
    ]
