# Generated by Django 5.2.14 on 2026-06-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_testing', '0002_uiaction_uielement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='页面名称')),
                ('path', models.CharField(blank=True, max_length=256, verbose_name='页面路径')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ui_testing.uipage', verbose_name='父级页面')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ui_testing.uisuite', verbose_name='套件')),
            ],
            options={
                'verbose_name': 'UI页面',
                'verbose_name_plural': 'UI页面',
                'ordering': ['suite_id', 'parent_id', 'sort_order', 'id'],
                'unique_together': {('suite', 'parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='uielement',
            name='page_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='ui_testing.uipage', verbose_name='页面节点'),
        ),
    ]
