# Generated by Codex on 2026-06-04

from django.db import migrations, models


def forward_fill_case_relations(apps, schema_editor):
    UiCase = apps.get_model("ui_testing", "UiCase")
    UiElement = apps.get_model("ui_testing", "UiElement")
    for case in UiCase.objects.all().iterator():
        if case.suite_id:
            case.suites.add(case.suite_id)
        element_ids = []
        for step in case.steps or []:
            element_id = step.get("element_id") if isinstance(step, dict) else None
            if element_id:
                element_ids.append(element_id)
        if element_ids:
            existing_ids = list(UiElement.objects.filter(id__in=set(element_ids)).values_list("id", flat=True))
            if existing_ids:
                case.elements.add(*existing_ids)


def backward_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ui_testing", "0003_uipage_uielement_page_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="uicase",
            name="elements",
            field=models.ManyToManyField(blank=True, related_name="ui_cases", to="ui_testing.uielement", verbose_name="关联定位元素"),
        ),
        migrations.AddField(
            model_name="uicase",
            name="suites",
            field=models.ManyToManyField(blank=True, related_name="case_memberships", to="ui_testing.uisuite", verbose_name="所属套件"),
        ),
        migrations.AlterField(
            model_name="uicase",
            name="suite",
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="cases", to="ui_testing.uisuite", verbose_name="兼容套件"),
        ),
        migrations.AlterModelOptions(
            name="uicase",
            options={"ordering": ["sort_order", "id"], "verbose_name": "UI测试用例", "verbose_name_plural": "UI测试用例"},
        ),
        migrations.RunPython(forward_fill_case_relations, backward_noop),
    ]
