# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_databaseconnection_db_type_and_more'),
        ('ui_testing', '0005_uiaction_created_by_uiaction_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='uisuite',
            table_comment='UI测试套件表：组织UI自动化用例的集合。',
        ),
        migrations.AlterModelTableComment(
            name='uicase',
            table_comment='UI测试用例表：维护浏览器、起始地址、步骤和断言。',
        ),
        migrations.AlterModelTableComment(
            name='uipage',
            table_comment='UI页面目录表：按套件维护页面树结构。',
        ),
        migrations.AlterModelTableComment(
            name='uielement',
            table_comment='UI定位元素表：维护页面元素的定位方式和选择器。',
        ),
        migrations.AlterModelTableComment(
            name='uiaction',
            table_comment='UI元素操作字典表：维护可复用的UI动作类型和默认参数。',
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='action',
            field=models.CharField(choices=[('goto', '打开页面'), ('click', '点击'), ('fill', '输入'), ('press', '按键'), ('select', '下拉选择'), ('check', '勾选'), ('uncheck', '取消勾选'), ('wait', '等待'), ('assert_visible', '断言可见'), ('assert_text', '断言文本'), ('assert_url', '断言 URL'), ('screenshot', '截图')], db_comment='动作编码。', default='click', max_length=32, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='default_value',
            field=models.CharField(blank=True, db_comment='默认输入值或期望值。', max_length=512, verbose_name='默认输入/期望'),
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='description',
            field=models.TextField(blank=True, db_comment='操作说明。', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='name',
            field=models.CharField(db_comment='操作名称。', max_length=128, verbose_name='操作名称'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='UI断言配置。', default=list, verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='browser',
            field=models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit')], db_comment='执行浏览器类型。', default='chromium', max_length=32, verbose_name='浏览器'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='name',
            field=models.CharField(db_comment='用例名称。', max_length=128, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='start_url',
            field=models.URLField(blank=True, db_comment='起始访问地址。', verbose_name='起始地址'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='steps',
            field=models.JSONField(blank=True, db_comment='UI操作步骤JSON。', default=list, verbose_name='步骤'),
        ),
        migrations.AlterField(
            model_name='uicase',
            name='suite',
            field=models.ForeignKey(db_comment='兼容旧结构的所属套件ID。', on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='ui_testing.uisuite', verbose_name='兼容套件'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='description',
            field=models.TextField(blank=True, db_comment='元素说明。', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='locator_type',
            field=models.CharField(choices=[('css', 'CSS'), ('text', 'Text'), ('role', 'Role'), ('xpath', 'XPath'), ('test_id', 'TestId')], db_comment='定位方式。', default='css', max_length=32, verbose_name='定位方式'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='name',
            field=models.CharField(db_comment='元素名称。', max_length=128, verbose_name='元素名称'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='page',
            field=models.CharField(blank=True, db_comment='页面名称快照。', max_length=128, verbose_name='页面'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='page_node',
            field=models.ForeignKey(blank=True, db_comment='所属页面节点ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='ui_testing.uipage', verbose_name='页面节点'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='selector',
            field=models.CharField(db_comment='定位表达式。', max_length=512, verbose_name='定位表达式'),
        ),
        migrations.AlterField(
            model_name='uielement',
            name='suite',
            field=models.ForeignKey(blank=True, db_comment='所属UI套件ID。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='ui_testing.uisuite', verbose_name='套件'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='description',
            field=models.TextField(blank=True, db_comment='页面说明。', verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='name',
            field=models.CharField(db_comment='页面名称。', max_length=128, verbose_name='页面名称'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='parent',
            field=models.ForeignKey(blank=True, db_comment='父级页面ID。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ui_testing.uipage', verbose_name='父级页面'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='path',
            field=models.CharField(blank=True, db_comment='页面路径。', max_length=256, verbose_name='页面路径'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='排序值。', default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='uipage',
            name='suite',
            field=models.ForeignKey(db_comment='所属UI套件ID。', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ui_testing.uisuite', verbose_name='套件'),
        ),
        migrations.AlterField(
            model_name='uisuite',
            name='description',
            field=models.TextField(blank=True, db_comment='套件说明。', verbose_name='套件描述'),
        ),
        migrations.AlterField(
            model_name='uisuite',
            name='name',
            field=models.CharField(db_comment='套件名称。', max_length=128, verbose_name='套件名称'),
        ),
        migrations.AlterField(
            model_name='uisuite',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='ui_suites', to='projects.project', verbose_name='项目'),
        ),
    ]
