# Generated by Django 5.2.14 on 2026-05-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_testing', '0001_initial'),
        ('projects', '0001_initial'),
        ('ui_testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('plan_type', models.CharField(choices=[('api', 'API'), ('ui', 'UI'), ('mixed', 'Mixed')], default='api', max_length=16)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('concurrency', models.PositiveSmallIntegerField(default=1)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('failure_strategy', models.CharField(choices=[('continue', 'Continue'), ('fast_fail', 'Fast fail')], default='continue', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('api_scenarios', models.ManyToManyField(blank=True, related_name='test_plans', to='api_testing.apiscenario')),
                ('api_suites', models.ManyToManyField(blank=True, related_name='test_plans', to='api_testing.apisuite')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to='projects.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project')),
                ('ui_suites', models.ManyToManyField(blank=True, related_name='test_plans', to='ui_testing.uisuite')),
            ],
            options={
                'ordering': ['project_id', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook')], default='manual', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='projects.environment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='test_runs.testplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scenario_name', models.CharField(blank=True, max_length=128)),
                ('step_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='test_runs.testrun')),
            ],
            options={
                'ordering': ['run_id', 'sort_order', 'id'],
            },
        ),
    ]
