# Generated by Django 5.2.14 on 2026-06-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_platform'),
        ('test_runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='api_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='module_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testplan',
            name='platform_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.platform'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=16),
        ),
    ]
