# Generated by Django 5.2.15 on 2026-06-08 00:46

from django.db import migrations, models


def normalize_run_status(apps, schema_editor):
    TestRun = apps.get_model("test_runs", "TestRun")
    TestRun.objects.filter(status="passed").update(status="completed")
    TestRun.objects.filter(status="canceled").update(status="failed")


class Migration(migrations.Migration):

    dependencies = [
        ('test_runs', '0003_testplan_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.RunPython(normalize_run_status, migrations.RunPython.noop),
    ]
