# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_databaseconnection_db_type_and_more'),
        ('test_runs', '0004_testrun_logs_alter_testrun_status'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='testplan',
            table_comment='测试计划表：组合接口套件、接口场景和UI套件形成可执行计划。',
        ),
        migrations.AlterModelTableComment(
            name='testrun',
            table_comment='测试执行记录表：一次测试计划运行的总记录和报告汇总。',
        ),
        migrations.AlterModelTableComment(
            name='testrunstep',
            table_comment='测试执行步骤表：一次测试运行中每个接口/场景/UI步骤的结果明细。',
        ),
        migrations.AlterField(
            model_name='testplan',
            name='api_ids',
            field=models.JSONField(blank=True, db_comment='计划覆盖的接口ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='concurrency',
            field=models.PositiveSmallIntegerField(db_comment='并发数。', default=1),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True, db_comment='计划说明。'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='默认运行环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='failure_strategy',
            field=models.CharField(choices=[('continue', 'Continue'), ('fast_fail', 'Fast fail')], db_comment='失败处理策略。', default='continue', max_length=16),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='module_ids',
            field=models.JSONField(blank=True, db_comment='计划覆盖的接口目录ID列表。', default=list),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='name',
            field=models.CharField(db_comment='计划名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='plan_type',
            field=models.CharField(choices=[('api', 'API'), ('ui', 'UI'), ('mixed', 'Mixed')], db_comment='计划类型：API/UI/混合。', default='api', max_length=16),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='platform_ref',
            field=models.ForeignKey(blank=True, db_comment='关联平台ID。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.platform'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='project',
            field=models.ForeignKey(db_comment='所属项目ID。', on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='retry_count',
            field=models.PositiveSmallIntegerField(db_comment='失败重试次数。', default=0),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], db_comment='计划状态。', default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='timeout_seconds',
            field=models.PositiveSmallIntegerField(db_comment='单步骤超时时间秒数。', default=30),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='variables',
            field=models.JSONField(blank=True, db_comment='计划级运行变量。', default=dict),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='celery_task_id',
            field=models.CharField(blank=True, db_comment='异步任务ID。', max_length=128),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='duration_ms',
            field=models.PositiveIntegerField(db_comment='总耗时毫秒。', default=0),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='本次运行环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='projects.environment'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='error_message',
            field=models.TextField(blank=True, db_comment='失败错误信息。'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_comment='结束时间。', null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='logs',
            field=models.JSONField(blank=True, db_comment='执行日志列表。', default=list),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='plan',
            field=models.ForeignKey(db_comment='关联测试计划ID。', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='test_runs.testplan'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='report',
            field=models.JSONField(blank=True, db_comment='执行报告JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='started_at',
            field=models.DateTimeField(blank=True, db_comment='开始时间。', null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_comment='执行状态。', default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='summary',
            field=models.JSONField(blank=True, db_comment='执行摘要JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook')], db_comment='触发方式：手动/定时/Webhook。', default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='assertions',
            field=models.JSONField(blank=True, db_comment='断言执行结果。', default=list),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='duration_ms',
            field=models.PositiveIntegerField(db_comment='步骤耗时毫秒。', default=0),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='error_message',
            field=models.TextField(blank=True, db_comment='步骤错误信息。'),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='logs',
            field=models.JSONField(blank=True, db_comment='步骤日志列表。', default=list),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='request',
            field=models.JSONField(blank=True, db_comment='实际请求信息。', default=dict),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='response',
            field=models.JSONField(blank=True, db_comment='实际响应信息。', default=dict),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='run',
            field=models.ForeignKey(db_comment='所属执行记录ID。', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='test_runs.testrun'),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='scenario_name',
            field=models.CharField(blank=True, db_comment='所属场景名称。', max_length=128),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='sort_order',
            field=models.PositiveIntegerField(db_comment='步骤排序值。', default=0),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_comment='步骤执行状态。', default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='testrunstep',
            name='step_name',
            field=models.CharField(db_comment='步骤名称。', max_length=128),
        ),
    ]
