# Generated by Django 5.2.15 on 2026-06-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_notification_templates_and_logs"),
        ("test_runs", "0006_run_suite_remove_testplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                db_comment="来源定时任务ID。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="scheduling.scheduledplan",
            ),
        ),
    ]
