# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersession_token_key_authtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='authtoken',
            table_comment='登录Token表：保存用户API访问Token。',
        ),
        migrations.AlterModelTableComment(
            name='permission',
            table_comment='权限点表：平台功能权限的最小授权单元。',
        ),
        migrations.AlterModelTableComment(
            name='role',
            table_comment='角色表：用户角色及其权限集合。',
        ),
        migrations.AlterModelTableComment(
            name='userprofile',
            table_comment='用户资料表：扩展Django用户的角色、状态和安全信息。',
        ),
        migrations.AlterModelTableComment(
            name='usersession',
            table_comment='用户会话表：记录登录设备、IP和Token活跃状态。',
        ),
        migrations.AlterModelTableComment(
            name='loginattempt',
            table_comment='登录尝试表：记录登录成功/失败和失败原因。',
        ),
        migrations.AlterModelTableComment(
            name='auditlog',
            table_comment='审计日志表：记录用户关键操作和目标对象。',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', '登录'), ('logout', '退出'), ('create', '创建'), ('update', '修改'), ('delete', '删除'), ('enable', '启用'), ('disable', '禁用'), ('reset_password', '重置密码'), ('force_logout', '强制下线'), ('export', '导出')], db_comment='操作类型。', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.JSONField(blank=True, db_comment='操作详情JSON。', default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_comment='操作来源IP。', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_comment='业务模块。', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(db_comment='操作是否成功。', default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='summary',
            field=models.CharField(db_comment='操作摘要。', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, db_comment='目标对象ID。', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, db_comment='目标对象类型。', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, db_comment='操作用户ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, db_comment='浏览器User-Agent。'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, db_comment='操作用户名快照。', max_length=150),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_comment='Token创建时间。'),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(db_comment='Token字符串主键。', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.OneToOneField(db_comment='绑定用户ID。', on_delete=django.db.models.deletion.CASCADE, related_name='strong_auth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_comment='来源IP地址。', null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='reason',
            field=models.CharField(blank=True, db_comment='失败或拦截原因。', max_length=255),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='success',
            field=models.BooleanField(db_comment='是否登录成功。', default=False),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, db_comment='浏览器User-Agent。'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(db_comment='尝试登录的用户名。', max_length=150),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('read', '读取'), ('write', '写入'), ('delete', '删除'), ('export', '导出'), ('execute', '执行'), ('admin', '管理')], db_comment='权限动作。', max_length=16),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(db_comment='权限编码，如 api.read。', max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(blank=True, db_comment='权限说明。', max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(db_comment='权限所属模块。', max_length=64),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(db_comment='权限名称。', max_length=64),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(db_comment='角色编码。', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, db_comment='角色说明。', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_builtin',
            field=models.BooleanField(db_comment='是否系统内置角色。', default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_comment='角色名称。', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, db_comment='头像URL。'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='failed_login_count',
            field=models.PositiveIntegerField(db_comment='连续登录失败次数。', default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_comment='锁定截止时间。', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(db_comment='是否必须修改密码。', default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(db_comment='用户昵称。', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, db_comment='最近密码修改时间。', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, db_comment='手机号。', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, db_comment='用户角色ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('disabled', '禁用'), ('locked', '锁定')], db_comment='账号状态。', default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_comment='关联Django用户ID。', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_work_id',
            field=models.CharField(blank=True, db_comment='企业微信用户ID。', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device',
            field=models.CharField(blank=True, db_comment='登录设备描述。', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_comment='会话过期时间。', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_comment='登录IP地址。', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_comment='最近活跃时间。', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_comment='会话撤销时间。', null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token_key',
            field=models.CharField(db_comment='登录Token Key。', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(db_comment='关联用户ID。', on_delete=django.db.models.deletion.CASCADE, related_name='account_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, db_comment='浏览器User-Agent。'),
        ),
    ]
