# Generated by Django 5.2.14 on 2026-05-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_runs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='调度名称')),
                ('cron', models.CharField(max_length=128, verbose_name='Cron表达式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='test_runs.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试调度',
                'verbose_name_plural': '测试调度',
                'ordering': ['plan_id', 'name'],
            },
        ),
    ]
