# Generated by Django 5.2.15 on 2026-06-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_scheduledplan_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledplan',
            name='last_run_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='最近执行ID'),
        ),
        migrations.AddField(
            model_name='scheduledplan',
            name='last_status',
            field=models.CharField(blank=True, max_length=16, verbose_name='最近执行状态'),
        ),
        migrations.AddField(
            model_name='scheduledplan',
            name='run_count',
            field=models.PositiveIntegerField(default=0, verbose_name='执行次数'),
        ),
    ]
