# Generated by Django 5.2.15 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_databaseconnection_db_type'),
        ('scheduling', '0003_scheduledplan_last_run_id_scheduledplan_last_status_and_more'),
        ('test_runs', '0004_testrun_logs_alter_testrun_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledplan',
            options={'ordering': ['plan_id', 'name'], 'verbose_name': 'Scheduled test plan', 'verbose_name_plural': 'Scheduled test plans'},
        ),
        migrations.AddField(
            model_name='scheduledplan',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_plans', to='projects.environment', verbose_name='Run environment'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='cron',
            field=models.CharField(max_length=128, verbose_name='Cron expression'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last run at'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_run_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Last run ID'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_status',
            field=models.CharField(blank=True, max_length=16, verbose_name='Last status'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Schedule name'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next run at'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='test_runs.testplan', verbose_name='Test plan'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='run_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Run count'),
        ),
    ]
