# Generated by Django 5.2.14 on 2026-06-13 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_databaseconnection_db_type_and_more'),
        ('scheduling', '0004_alter_scheduledplan_options_and_more'),
        ('test_runs', '0005_alter_testplan_api_ids_alter_testplan_concurrency_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='scheduledplan',
            table_comment='定时任务表：按Cron定期触发测试计划执行。',
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='cron',
            field=models.CharField(db_comment='Cron表达式。', max_length=128, verbose_name='Cron expression'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='environment',
            field=models.ForeignKey(blank=True, db_comment='定时任务运行环境ID。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_plans', to='projects.environment', verbose_name='Run environment'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='is_active',
            field=models.BooleanField(db_comment='是否启用。', default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_run_at',
            field=models.DateTimeField(blank=True, db_comment='最近执行时间。', null=True, verbose_name='Last run at'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_run_id',
            field=models.PositiveBigIntegerField(blank=True, db_comment='最近执行记录ID。', null=True, verbose_name='Last run ID'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='last_status',
            field=models.CharField(blank=True, db_comment='最近执行状态。', max_length=16, verbose_name='Last status'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='name',
            field=models.CharField(db_comment='任务名称。', max_length=128, verbose_name='Schedule name'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_comment='下次预计执行时间。', null=True, verbose_name='Next run at'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='plan',
            field=models.ForeignKey(db_comment='关联测试计划ID。', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='test_runs.testplan', verbose_name='Test plan'),
        ),
        migrations.AlterField(
            model_name='scheduledplan',
            name='run_count',
            field=models.PositiveIntegerField(db_comment='累计执行次数。', default=0, verbose_name='Run count'),
        ),
    ]
