# Generated by Django 5.2.15 on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_databaseconnection_db_type_and_more"),
        ("scheduling", "0006_scheduledplan_suite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledplan",
            name="cron",
            field=models.CharField(db_comment="Cron表达式。", max_length=128, verbose_name="Cron表达式"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                db_comment="定时任务运行环境ID。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_plans",
                to="projects.environment",
                verbose_name="运行环境",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="is_active",
            field=models.BooleanField(db_comment="是否启用。", default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="last_run_at",
            field=models.DateTimeField(blank=True, db_comment="最近执行时间。", null=True, verbose_name="最近执行时间"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="last_run_id",
            field=models.PositiveBigIntegerField(blank=True, db_comment="最近执行记录ID。", null=True, verbose_name="最近执行记录ID"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="last_status",
            field=models.CharField(blank=True, db_comment="最近执行状态。", max_length=16, verbose_name="最近执行状态"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="name",
            field=models.CharField(db_comment="任务名称。", max_length=128, verbose_name="任务名称"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="next_run_at",
            field=models.DateTimeField(blank=True, db_comment="下次预计执行时间。", null=True, verbose_name="下次执行时间"),
        ),
        migrations.AlterField(
            model_name="scheduledplan",
            name="run_count",
            field=models.PositiveIntegerField(db_comment="累计执行次数。", default=0, verbose_name="累计执行次数"),
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("feishu", "飞书")],
                        db_comment="通知类型，当前支持飞书。",
                        default="feishu",
                        max_length=32,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "webhook_ciphertext",
                    models.TextField(db_comment="Webhook加密密文，不允许明文落库或列表返回。", verbose_name="Webhook密文"),
                ),
                ("is_active", models.BooleanField(db_comment="是否启用该通知通道。", default=True, verbose_name="是否启用")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息通知",
                "verbose_name_plural": "消息通知",
                "db_table_comment": "消息通知表：维护平台可复用的通知通道配置。",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="scheduledplan",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联消息通知ID，定时任务推送能力使用。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduled_plans",
                to="scheduling.notificationchannel",
                verbose_name="消息通知",
            ),
        ),
    ]
