# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models


def normalize_legacy_notifications(apps, schema_editor):
    NotificationChannel = apps.get_model("scheduling", "NotificationChannel")
    for item in NotificationChannel.objects.all():
        item.name = item.name or f"历史通知-{item.id}"
        item.notification_type = "api_testing"
        item.push_platform = "feishu"
        item.signature_ciphertext = item.signature_ciphertext or ""
        item.save(update_fields=["name", "notification_type", "push_platform", "signature_ciphertext"])


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_alter_scheduledplan_cron_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationchannel",
            name="name",
            field=models.CharField(db_comment="通知名称。", default="默认通知", max_length=64, verbose_name="通知名称"),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="push_platform",
            field=models.CharField(
                choices=[("feishu", "飞书"), ("wechat_work", "企业微信"), ("dingtalk", "钉钉")],
                db_comment="推送平台：飞书、企业微信或钉钉。",
                default="feishu",
                max_length=32,
                verbose_name="推送平台",
            ),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="signature_ciphertext",
            field=models.TextField(blank=True, db_comment="飞书签名校验密文，不允许明文落库或列表返回。", verbose_name="签名校验密文"),
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="notification_type",
            field=models.CharField(
                choices=[("api_testing", "接口测试"), ("ui_testing", "UI测试")],
                db_comment="通知类型：接口测试或UI测试。",
                default="api_testing",
                max_length=32,
                verbose_name="通知类型",
            ),
        ),
        migrations.RunPython(normalize_legacy_notifications, migrations.RunPython.noop),
    ]
