# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models


def migrate_single_notification_to_many(apps, schema_editor):
    ScheduledPlan = apps.get_model("scheduling", "ScheduledPlan")
    for plan in ScheduledPlan.objects.exclude(notification_id__isnull=True):
        plan.notifications.add(plan.notification_id)


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_notificationchannel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledplan",
            name="notifications",
            field=models.ManyToManyField(blank=True, related_name="scheduled_plans", to="scheduling.notificationchannel", verbose_name="消息通知"),
        ),
        migrations.RunPython(migrate_single_notification_to_many, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="scheduledplan",
            name="notification",
        ),
    ]
