# Generated by Django 5.2.15 on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_template(apps, schema_editor):
    NotificationTemplate = apps.get_model("scheduling", "NotificationTemplate")
    NotificationTemplate.objects.get_or_create(
        name="定时任务执行结果",
        defaults={
            "biz_type": "schedule_run",
            "push_platform": "general",
            "title_template": "【{{status_text}}】{{suite_name}} - {{schedule_name}}",
            "content_template": (
                "任务名称：{{schedule_name}}\n"
                "测试套件：{{suite_name}}\n"
                "运行环境：{{environment_name}}\n"
                "触发方式：{{trigger_type}}\n"
                "执行结果：{{status_text}}\n"
                "总数：{{total_count}}\n"
                "通过：{{passed_count}}\n"
                "失败：{{failed_count}}\n"
                "跳过：{{skipped_count}}\n"
                "通过率：{{pass_rate}}%\n"
                "总耗时：{{duration}}\n"
                "开始时间：{{started_at}}\n"
                "结束时间：{{finished_at}}\n"
                "报告地址：{{report_url}}"
            ),
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0009_scheduledplan_notifications"),
        ("test_runs", "0006_run_suite_remove_testplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledplan",
            name="notify_on",
            field=models.CharField(
                choices=[("disabled", "不推送"), ("always", "成功/失败都推送"), ("failed_only", "仅失败推送")],
                db_comment="推送条件。",
                default="disabled",
                max_length=24,
                verbose_name="推送条件",
            ),
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(db_comment="模板名称。", max_length=64, verbose_name="模板名称")),
                (
                    "biz_type",
                    models.CharField(
                        choices=[("schedule_run", "定时任务执行结果")],
                        db_comment="适用业务场景。",
                        default="schedule_run",
                        max_length=32,
                        verbose_name="适用业务",
                    ),
                ),
                (
                    "push_platform",
                    models.CharField(
                        choices=[("general", "通用"), ("feishu", "飞书"), ("wechat_work", "企业微信"), ("dingtalk", "钉钉"), ("email", "邮箱")],
                        db_comment="适用推送平台，通用表示所有平台可用。",
                        default="general",
                        max_length=32,
                        verbose_name="推送平台",
                    ),
                ),
                ("title_template", models.CharField(db_comment="标题模板，支持白名单变量。", max_length=160, verbose_name="标题模板")),
                ("content_template", models.TextField(db_comment="内容模板，支持白名单变量。", verbose_name="内容模板")),
                ("is_active", models.BooleanField(db_comment="是否启用。", default=True, verbose_name="是否启用")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息模板",
                "verbose_name_plural": "消息模板",
                "db_table_comment": "消息模板表：维护不同业务场景下可复用的消息内容模板。",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSendLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("title", models.CharField(db_comment="实际发送标题。", max_length=200, verbose_name="发送标题")),
                ("content", models.TextField(db_comment="实际发送内容。", verbose_name="发送内容")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败"), ("skipped", "跳过")],
                        db_comment="发送状态。",
                        default="failed",
                        max_length=16,
                        verbose_name="发送状态",
                    ),
                ),
                ("error_message", models.TextField(blank=True, db_comment="失败原因。", verbose_name="失败原因")),
                ("retry_count", models.PositiveIntegerField(db_comment="重试次数。", default=0, verbose_name="重试次数")),
                ("sent_at", models.DateTimeField(blank=True, db_comment="发送时间。", null=True, verbose_name="发送时间")),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        db_comment="关联消息通知ID。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_logs",
                        to="scheduling.notificationchannel",
                        verbose_name="消息通知",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        db_comment="关联定时任务ID。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="scheduling.scheduledplan",
                        verbose_name="定时任务",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="关联执行记录ID。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="test_runs.testrun",
                        verbose_name="执行记录",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后修改人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        db_comment="关联消息模板ID。",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_logs",
                        to="scheduling.notificationtemplate",
                        verbose_name="消息模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息发送记录",
                "verbose_name_plural": "消息发送记录",
                "db_table_comment": "消息发送记录表：记录每次消息推送的结果和错误原因。",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scheduledplan",
            name="notification_template",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联消息模板ID。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_plans",
                to="scheduling.notificationtemplate",
                verbose_name="消息模板",
            ),
        ),
    ]
