# Generated by Django 5.2.15 on 2026-06-23 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_notification_templates_and_logs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="push_platform",
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联消息通知ID，用于界定模板实际推送通道。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="scheduling.notificationchannel",
                verbose_name="消息通知",
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="content_template",
            field=models.TextField(db_comment="内容模板，支持HTML富文本和白名单变量。", verbose_name="内容模板"),
        ),
    ]
